# Generated by Django 4.2.17 on 2025-01-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yasviapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
