# Generated by Django 4.2.17 on 2025-01-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasviapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(upload_to='locations/'),
        ),
    ]
