# Generated by Django 4.2.17 on 2025-01-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yasviapp', '0004_alter_location_description_alter_location_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
        migrations.DeleteModel(
            name='Segment',
        ),
    ]
