# Generated by Django 4.2.17 on 2025-01-06 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yasviapp', '0005_remove_roomimage_category_remove_roomimage_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yasviapp.category')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yasviapp.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yasviapp.category')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yasviapp.destination')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yasviapp.segment')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yasviapp.destination'),
        ),
    ]
