# Generated by Django 4.2.17 on 2025-01-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasviapp', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='segment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='segment_image',
            field=models.ImageField(blank=True, null=True, upload_to='segments/'),
        ),
    ]
