# Generated by Django 4.2.17 on 2025-01-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasviapp', '0007_remove_destination_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='destination',
            name='order',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
