# Generated by Django 4.2.17 on 2025-01-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasviapp', '0008_alter_destination_options_destination_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
