# Generated by Django 4.2.17 on 2025-01-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yasviapp', '0009_destination_description_alter_destination_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={},
        ),
        migrations.RemoveField(
            model_name='destination',
            name='description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='order',
        ),
    ]
