# Generated by Django 4.2.17 on 2025-01-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasviapp', '0013_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='camping_images/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
