# Generated by Django 4.2.17 on 2025-01-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasviapp', '0014_campingimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='description',
            new_name='details',
        ),
        migrations.AddField(
            model_name='package',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
