# Generated by Django 4.2.17 on 2025-01-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasviapp', '0016_campingimage_amount_campingimage_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campingimage',
            name='status',
            field=models.BooleanField(choices=[(True, 'Available'), (False, 'Not Available')], default=True),
        ),
    ]
